name: GoRest API Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI-Environment-Cloudflare-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run cloudfare check 
        run: |

          npx newman run "collections/03-CI-Environment-Check.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json,htmlextra \
          --reporter-json-export reports/report-ci-check.json \
          --reporter-htmlextra-export reports/report-ci-check.html

      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Cloud-results
          path: reports/
          retention-days: 30

  Authentication-Validation:
    needs: CI-Environment-Cloudflare-check
    if: failure() 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Auth Tests
        run: |
          
          newman run collections/01-Authentication-Validation.postman_collection.json \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json \
          --reporter-json-export reports/report-auth.json


      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Auth-validation-test-results
          path: reports/
          retention-days: 30


  E2E-Flow:
    needs: CI-Environment-Cloudflare-check
    if: failure() 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run E2E tests
        run: |

          newman run "collections/02-End-to-End Flow.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json \
          --reporter-json-export reports/report-e2e.json

      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: E2E-test-results
          path: reports/
          retention-days: 30

