name: GoRest API Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  CI-Environment-Cloudflare-check:
    runs-on: ubuntu-latest
    outputs:
      api_accessible: ${{ steps.set-output.outputs.accessible }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      # Collection 01 passes when API is blocked (403/503), fails when accessible (200).
      # continue-on-error keeps the job alive and saves got failure value
      - name: Run cloudfare check
        id: cf-check
        continue-on-error: true
        run: |

          npx newman run "collections/01-CI-Environment-Check.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json,htmlextra \
          --reporter-json-export reports/report-ci-check.json \
          --reporter-htmlextra-export reports/report-ci-check.html

      #Verify Collection 03 response and set creates $GITHUB_OUTPUT
      - name: Set API accessibility output
        id: set-output
        run: |
          if [ "${{ steps.cf-check.outcome }}" = "failure" ]; then
            echo "accessible=true" >> $GITHUB_OUTPUT
            echo "API is accessible — proceeding with tests"
          else
            echo "accessible=false" >> $GITHUB_OUTPUT
            echo "::warning::GoRest blocked by Cloudflare — skipping API tests"
          fi

      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Cloud-results
          path: reports/
          retention-days: 30

  Authentication-Validation:
    needs: CI-Environment-Cloudflare-check
    if: needs.CI-Environment-Cloudflare-check.outputs.api_accessible == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Auth Tests
        run: |
          
          newman run collections/02-Authentication-Validation.postman_collection.json \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json \
          --reporter-json-export reports/report-auth.json


      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Auth-validation-test-results
          path: reports/
          retention-days: 30


  E2E-Flow:
    needs: CI-Environment-Cloudflare-check
    if: needs.CI-Environment-Cloudflare-check.outputs.api_accessible == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run E2E tests
        run: |

          newman run "collections/03-End-to-End Flow.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --iteration-data data/InputTestData.csv \
          --reporters cli,json \
          --reporter-json-export reports/report-e2e.json

      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: E2E-test-results
          path: reports/
          retention-days: 30

  Negative-Validation:
    needs: CI-Environment-Cloudflare-check
    if: needs.CI-Environment-Cloudflare-check.outputs.api_accessible == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Negative Validation tests
        run: |

          newman run "collections/04-Negative-Validation.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json \
          --reporter-json-export reports/report-negative.json

      - name: TR screenshots
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: Negative-validation-test-results
          path: reports/
          retention-days: 30

