name: GoRest API Test Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Creates reports folder as folder doesn't exist.
      - name: Create reports directory
        run: mkdir -p reports

      - name: Run API Tests
        run: |
          # Updated
          newman run collections/01-Authentication-Validation.postman_collection.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          # Updated
          --reporters cli,json \
          # Updated
          --reporter-json-export reports/report-auth.json

          # Updated
          newman run "collections/02-End-to-End Flow.postman_collection.json" \
          --environment environments/devGoRest.postman_environment.json \
          --env-var "authToken=${{ secrets.GOREST_TOKEN }}" \
          --reporters cli,json \
          --reporter-json-export reports/report-e2e.json

      - name: TR screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: reports/
          retention-days: 30